section3:
  search_terms:
    - working conditions are safe and hygienic
    - current systems and evidence examined
section4:
  search_terms:
    - child labour shall not be used
    - current systems and evidence examined